### PR TITLE
Docs and misc

### PR DESCRIPTION
**Pull request by Erotemic**
With respect to #21, this moves the plt imports inside the functions, so the plot code can be imported at startup time. In the issue you mentioned the submodule logic takes care of this, and you're right, so I can drop 183a2a9 if necessary. 

Also in the `__init__.py` file I noticed there were two definitions of pyprime, one was the submodule and the other was the function. I removed that ambiguity by adding the `--nomods` flag to `mkinit`, which only exposes attributes and not the parent modules. However, there is still an ambiguity by exposing the `pyprime` attribute at the top level. There is now effectively no way to reference the `pyprime` module, which I believe breaks some of the examples. This can either be fixed by (1) reverting the mkinit change, (2) changing the name of the submodule to something like "core", (3) removing the pyprime function from the `__init__.py` file or (4) being ok with the loss of that module reference and declaring that core functions should always be used via the top level. Personally I prefer option 2. 

Almost lastly, I added several doctests to demonstrate usage of the module. These can be run automatically on TravisCI via installing [xdoctest](https://github.com/Erotemic/xdoctest) from pypi and including the lines `coverage run --source=nprime.pyprime -m xdoctest nprime` or if you switched to pytest you could test everything with one command:

```bash
pip install pytest pytest-cov xdoctest
pytest --xdoctest --cov=nprime --cov-report xml nprime tests
```

But either way, the examples should be helpful. 

Actually lastly, I slightly improved the efficiency of `generate_primes` by rougly (1.5x). I stored the sqrt computation in a variable to prevent recalculation and used pythonic iterables rather than index based loops. 

```python
def generate_primes_new(upper=0):
    if upper >= 2:
        primes = [2]
        for n in range(3, upper + 1):
            # We only check if n is divided by the previous primes
            sqrt_n = pow(n, 0.5)
            found = None
            # Test if any previous primes divides n
            for p in primes:
                if sqrt_n < p:
                    break
                if n % p == 0:
                    found = p
                    break  # not prime
            if found is None:
                primes.append(n)  # must be prime
    else:
        primes = []
    return primes


def generate_primes_old(upper=0):
    if upper >= 2:
        primes = [2]

        for n in range(3, upper + 1):
            # We only check if n is divided by the previous primes
            k = 0
            sqrt_n = pow(n, 0.5)

            while primes[k] <= sqrt_n and n % primes[k] != 0:
                k += 1

            # if a number has no dividers, last prime[k] of loop is over n's square root
            if sqrt_n < primes[k]:
                primes.append(n)
    else:
        primes = []

    return primes

import timerit
ti = timerit.Timerit(20, bestof=3, verbose=2)

upper = 50000
for timer in ti.reset('old'):
    with timer:
        list(generate_primes_old(upper))

for timer in ti.reset('new'):
    with timer:
        list(generate_primes_new(upper))
```

```
Timed old for: 20 loops, best of 3
    time per loop: best=66.917 ms, mean=67.662 ± 1.0 ms
Timed new for: 20 loops, best of 3
    time per loop: best=42.258 ms, mean=43.816 ± 1.0 ms
```

### CODE REVIEW

**Comment by sylhare** [comment]
Oh interesting!
I'll take a look at all that, thank you very much :)

**Comment by sylhare** [comment]
Yup, I like it I'll play with it more and add it to the pipeline.
However I am not sure what this ` >>> # xdoctest: +IGNORE_WANT` is for.

**Comment by Erotemic** [comment]
The `>>> # xdoctest: +IGNORE_WANT` is a [directive](https://xdoctest.readthedocs.io/en/latest/autoapi/xdoctest/directive/index.html) that prevents the xdoctest checker from failing if what we "got" is different from what we "want" in the context of the doctest output. This is because the function is probabilistic, so I wouldn't want the dashboards to fail in freak instances where the output is different.

**Comment by sylhare** [comment]
Oh ok I see, well since there is a good/high chance of those test passing with the default setting of `t=100`, that won't make them too flaky. 😉

**Pull request merged**
